[project]
name = "evolutionary-lending"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.lending-governance]
path = "contracts/lending-governance.clar"
depends_on = []

[contracts.lending-risk-assessment]
path = "contracts/lending-risk-assessment.clar"
depends_on = []

[contracts.lending-pool-registry]
path = "contracts/lending-pool-registry.clar"
depends_on = []

[contracts.lending-performance-tracker]
path = "contracts/lending-performance-tracker.clar"
depends_on = []

[contracts.lending-rewards-distributor]
path = "contracts/lending-rewards-distributor.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
